// tests/board/test_gif_timing.h
//
// The animation schedule: which frame is due when, and what the file actually
// says it should be.
//
// The container is parsed from hand-built bytes rather than a checked-in GIF, so
// every case here is a claim about the format written out in full -- a delay of
// 7 hundredths, a missing graphic control extension, a loop count of 3 -- rather
// than a property of one particular file. That also means no binary fixture in
// the repo and nothing that rots when a tool rewrites it.
#pragma once

#include "board/gif_timing.h"
#include "board/gif_timing_parse.h"
#include "../test_lib.h"

namespace referentia::tests {
namespace gif_ns = referentia::board;

using gif_ns::FrameAt;
using gif_ns::GifTiming;

// ---------------------------------------------------------------------------
// A minimal GIF builder
// ---------------------------------------------------------------------------

/**
 * Assembles a GIF89a from parts, so each test can state exactly one thing about
 * the format without a real encoder's output getting in the way.
 */
struct GifBuilder {
  std::vector<unsigned char> bytes;

  void u8(unsigned v) { bytes.push_back(static_cast<unsigned char>(v)); }
  void u16(unsigned v) {
    u8(v & 0xFF);
    u8((v >> 8) & 0xFF);
  }
  void raw(const char* s) {
    for (const char* p = s; *p; ++p) u8(static_cast<unsigned char>(*p));
  }

  /** Header, logical screen descriptor, no global colour table. */
  GifBuilder& screen(int w = 4, int h = 4) {
    raw("GIF89a");
    u16(w);
    u16(h);
    u8(0);  // packed: no global colour table
    u8(0);  // background colour index
    u8(0);  // pixel aspect ratio
    return *this;
  }

  /**
   * A graphic control extension carrying `delay_units` hundredths of a second.
   *
   * The one before a frame, which is where a frame's delay actually lives. The
   * transparent colour index is 0, so the packed byte is 0.
   */
  GifBuilder& delay(int delay_units) {
    u8(0x21);
    u8(0xF9);
    u8(4);
    u8(0);  // packed
    u16(delay_units);
    u8(0);  // transparent colour index
    u8(0);  // terminator
    return *this;
  }

  /**
   * The NETSCAPE2.0 application extension, which is where loops live.
   *
   * Byte-for-byte what a real encoder emits: an 11-byte block holding the whole
   * 11-character application id and no separate auth code. The spec allots 8
   * bytes of id plus 3 of auth, and getting this wrong is invisible until a
   * looping GIF plays for ever -- which is why the fixture is spelled out rather
   * than generated by a helper that would be trusted to have it right.
   */
  GifBuilder& loops(int loop_count) {
    u8(0x21);
    u8(0xFF);
    u8(11);
    raw("NETSCAPE2.0");
    // The sub-block: a 1 identifying the loop count, then the count itself.
    u8(3);
    u8(1);
    u16(loop_count);
    u8(0);
    return *this;
  }

  /** An image descriptor with a one-byte LZW payload: a frame. */
  GifBuilder& frame() {
    u8(0x2C);
    u16(0);
    u16(0);
    u16(4);
    u16(4);
    u8(0);  // packed: no local colour table
    u8(2);  // LZW minimum code size
    u8(1);  // sub-block length
    u8(0);  // sub-block payload
    u8(0);  // block terminator
    return *this;
  }

  GifBuilder& trailer() {
    u8(0x3B);
    return *this;
  }
};

// ---------------------------------------------------------------------------
// Frame selection
// ---------------------------------------------------------------------------

TEST(gif_timing_a_still_image_has_one_frame) {
  GifTiming timing;
  CHECK_EQ(FrameAt(timing, 0.0), 0);
  CHECK_EQ(FrameAt(timing, 10000.0), 0);
  CHECK(!timing.animated());
}

TEST(gif_timing_a_schedule_advances_through_its_frames) {
  GifTiming timing;
  timing.frame_delays_ms = {100, 100, 100};

  CHECK_EQ(FrameAt(timing, 0.0), 0);
  CHECK_EQ(FrameAt(timing, 99.0), 0);
  CHECK_EQ(FrameAt(timing, 100.0), 1);
  CHECK_EQ(FrameAt(timing, 199.0), 1);
  CHECK_EQ(FrameAt(timing, 200.0), 2);
  CHECK_EQ(FrameAt(timing, 299.0), 2);
}

TEST(gif_timing_a_looping_animation_wraps_for_ever) {
  // Delays are durations, so frame 0 holds for [0,100) and frame 1 for
  // [100,300). The boundary belongs to the frame that starts there.
  GifTiming timing;
  timing.frame_delays_ms = {100, 200};
  timing.loop_count = 0;  // forever

  CHECK_EQ(FrameAt(timing, 0.0), 0);
  CHECK_EQ(FrameAt(timing, 99.0), 0);
  CHECK_EQ(FrameAt(timing, 100.0), 1);
  CHECK_EQ(FrameAt(timing, 299.0), 1);
  CHECK_EQ(FrameAt(timing, 300.0), 0);
  // A second pass is identical to the first, which is the whole point.
  CHECK_EQ(FrameAt(timing, 600.0), 0);
  CHECK_EQ(FrameAt(timing, 100000.0), 1);
}

TEST(gif_timing_a_finite_animation_plays_its_repeats_then_stops) {
  GifTiming timing;
  timing.frame_delays_ms = {100, 100};
  timing.loop_count = 1;  // one repeat, so two plays

  CHECK_EQ(FrameAt(timing, 0.0), 0);
  CHECK_EQ(FrameAt(timing, 99.0), 0);
  CHECK_EQ(FrameAt(timing, 150.0), 1);
  CHECK_EQ(FrameAt(timing, 199.0), 1);
  // The second pass restarts, rather than continuing past the end of the first.
  CHECK_EQ(FrameAt(timing, 200.0), 0);
  CHECK_EQ(FrameAt(timing, 250.0), 0);
  CHECK_EQ(FrameAt(timing, 300.0), 1);
  // And it holds on the last frame once its plays are used up.
  CHECK_EQ(FrameAt(timing, 399.0), 1);
  CHECK_EQ(FrameAt(timing, 100000.0), 1);
}

TEST(gif_timing_a_zero_delay_frame_is_clamped_rather_than_instant) {
  // Browsers render a declared 0 as the shortest usable delay, not as zero.
  // Left alone it would make a whole animation's total duration zero, and the
  // wrap arithmetic would then be a division by zero.
  GifTiming timing;
  timing.frame_delays_ms = {gif_ns::SanitisedDelay(0),
                            gif_ns::SanitisedDelay(0)};

  CHECK_EQ(timing.frame_delays_ms[0], gif_ns::kMinFrameDelayMs);
  CHECK(gif_ns::TotalDurationMs(timing) > 0);
  CHECK_EQ(FrameAt(timing, 0.0), 0);
  CHECK_EQ(FrameAt(timing, 100000.0), 0);
}

TEST(gif_timing_playback_survives_a_negative_elapsed_time) {
  // A caller passing a delta computed across a clock that went backwards should
  // get the first frame, not a negative index.
  GifTiming timing;
  timing.frame_delays_ms = {100, 100};
  CHECK_EQ(FrameAt(timing, -500.0), 0);
}

TEST(gif_timing_playback_count_is_zero_for_a_forever_loop) {
  GifTiming timing;
  timing.frame_delays_ms = {100, 100};
  timing.loop_count = 0;
  CHECK_EQ(gif_ns::TotalPlays(timing), 0);
  CHECK(!gif_ns::FinishedPlaying(timing, 1000000.0));

  timing.loop_count = 2;
  CHECK_EQ(gif_ns::TotalPlays(timing), 3);
  CHECK(gif_ns::FinishedPlaying(timing, 600.0));
  CHECK(!gif_ns::FinishedPlaying(timing, 599.0));
}

// ---------------------------------------------------------------------------
// Reading the schedule out of a GIF
// ---------------------------------------------------------------------------

TEST(gif_parse_reads_each_frame_delay_in_order) {
  GifBuilder g;
  g.screen().delay(5).frame().delay(10).frame().delay(20).frame().trailer();

  const GifTiming timing = gif_ns::ParseGifTiming(g.bytes.data(), g.bytes.size());
  CHECK_EQ(timing.frame_delays_ms.size(), size_t{3});
  CHECK_EQ(timing.frame_delays_ms[0], 50);
  CHECK_EQ(timing.frame_delays_ms[1], 100);
  CHECK_EQ(timing.frame_delays_ms[2], 200);
}

TEST(gif_parse_a_frame_with_no_delay_extension_gets_the_default) {
  // The spec's own fallback, and what browsers use. A GIF written by a tool that
  // omits the graphic control extension is common enough to be worth the case.
  GifBuilder g;
  g.screen().frame().frame().trailer();

  const GifTiming timing = gif_ns::ParseGifTiming(g.bytes.data(), g.bytes.size());
  CHECK_EQ(timing.frame_delays_ms.size(), size_t{2});
  CHECK_EQ(timing.frame_delays_ms[0], gif_ns::kMinFrameDelayMs);
  CHECK_EQ(timing.frame_delays_ms[1], gif_ns::kMinFrameDelayMs);
}

TEST(gif_parse_reads_the_loop_count) {
  GifBuilder g;
  g.screen().loops(3).delay(10).frame().trailer();

  const GifTiming timing = gif_ns::ParseGifTiming(g.bytes.data(), g.bytes.size());
  CHECK_EQ(timing.loop_count, 3);
}

TEST(gif_parse_no_application_extension_means_loop_for_ever) {
  GifBuilder g;
  g.screen().delay(10).frame().trailer();

  const GifTiming timing = gif_ns::ParseGifTiming(g.bytes.data(), g.bytes.size());
  CHECK_EQ(timing.loop_count, 0);
}

TEST(gif_parse_a_global_colour_table_does_not_shift_the_frame_offsets) {
  // The packed field in the screen descriptor says whether a colour table
  // follows, and it is up to 768 bytes. Reading a delay without accounting for
  // it lands the parse in the middle of the palette and produces a schedule for
  // the wrong frames -- so this pins the stride.
  GifBuilder g;
  g.raw("GIF89a");
  g.u16(4);
  g.u16(4);
  g.u8(0x80 | 0x01);  // global colour table present, 2^(1+1) = 4 entries
  g.u8(0);
  g.u8(0);
  for (int i = 0; i < 4 * 3; ++i) g.u8(0xAB);
  g.delay(7).frame().trailer();

  const GifTiming timing = gif_ns::ParseGifTiming(g.bytes.data(), g.bytes.size());
  CHECK_EQ(timing.frame_delays_ms.size(), size_t{1});
  CHECK_EQ(timing.frame_delays_ms[0], 70);
}

TEST(gif_parse_a_delayed_then_undelayed_frame_does_not_repeat_the_delay) {
  // The graphic control extension applies to the next image only. Carrying it
  // forward would make every frame after the first as slow as the first.
  GifBuilder g;
  g.screen().delay(20).frame().frame().delay(5).frame().trailer();

  const GifTiming timing = gif_ns::ParseGifTiming(g.bytes.data(), g.bytes.size());
  CHECK_EQ(timing.frame_delays_ms.size(), size_t{3});
  CHECK_EQ(timing.frame_delays_ms[0], 200);
  CHECK_EQ(timing.frame_delays_ms[1], gif_ns::kMinFrameDelayMs);
  CHECK_EQ(timing.frame_delays_ms[2], 50);
}

TEST(gif_parse_a_truncated_gif_yields_no_schedule_rather_than_a_wrong_one) {
  GifBuilder g;
  g.screen().delay(10).frame();
  // Cut off mid-container: no trailer, and the last frame is complete.
  const std::vector<unsigned char> cut(g.bytes.begin(),
                                      g.bytes.end() - 1);
  const GifTiming timing = gif_ns::ParseGifTiming(cut.data(), cut.size());
  CHECK(timing.frame_delays_ms.size() <= size_t{1});
}

TEST(gif_parse_a_non_gif_is_not_parsed_as_one) {
  // A .gif that is actually a JPEG is common on the web. Parsing it as a
  // container yields nonsense delays rather than an error, so the magic is
  // checked first.
  const unsigned char jpeg[] = {0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x10, 0x00, 0x00};
  CHECK(!gif_ns::IsGifData(jpeg, sizeof(jpeg)));
  const GifTiming timing = gif_ns::ParseGifTiming(jpeg, sizeof(jpeg));
  CHECK(timing.frame_delays_ms.empty());
  CHECK_EQ(timing.loop_count, 0);
}

TEST(gif_parse_nothing_at_all_is_not_a_gif) {
  CHECK(!gif_ns::IsGifData(nullptr, 0));
  const unsigned char tiny[] = {'G', 'I', 'F'};
  CHECK(!gif_ns::IsGifData(tiny, sizeof(tiny)));
  const GifTiming timing = gif_ns::ParseGifTiming(tiny, sizeof(tiny));
  CHECK(timing.frame_delays_ms.empty());
}

TEST(gif_parse_a_parsed_schedule_agrees_with_the_frame_selection) {
  // End to end through both halves: the delays the file declares, and the frame
  // that those delays imply at a given moment.
  GifBuilder g;
  g.screen().delay(5).frame().delay(5).frame().delay(5).frame().loops(2).trailer();

  const GifTiming timing = gif_ns::ParseGifTiming(g.bytes.data(), g.bytes.size());
  CHECK(timing.animated());
  CHECK_EQ(timing.frame_delays_ms.size(), size_t{3});
  CHECK_EQ(gif_ns::TotalDurationMs(timing), 150);

  CHECK_EQ(FrameAt(timing, 0.0), 0);
  CHECK_EQ(FrameAt(timing, 50.0), 1);
  CHECK_EQ(FrameAt(timing, 100.0), 2);
  CHECK_EQ(FrameAt(timing, 150.0), 0);   // second play
  CHECK_EQ(FrameAt(timing, 200.0), 1);
  CHECK_EQ(FrameAt(timing, 250.0), 2);
  // 3 plays of 150ms: it ends, on the last frame.
  CHECK_EQ(FrameAt(timing, 450.0), 2);
  CHECK(gif_ns::FinishedPlaying(timing, 450.0));
  CHECK(!gif_ns::FinishedPlaying(timing, 449.0));
}

}  // namespace referentia::tests
